Simplify max_zoom logics in Map and TileLayer
jupyter-widgets/ipyleaflet pull request #965
Opened 2022-04-15 09:16 UTC by HaudinFlorence

Simplify max_zoom logics in Map and TileLayer.

Add changes in Map and TileLayer options to fit the one's of LeafletJS.
Updates of the related docstrings.

2022-04-15 09:22 UTC, martinRenou commented on js/src/Map.js
>        center: DEFAULT_LOCATION,
You should probably reflect the `center` change you made Python-side by setting a default value of `null` here

2022-04-15 09:22 UTC, martinRenou commented on js/src/Map.js
> +          );  this.touch();
Can you describe a bit why those changes are needed?

2022-04-16 13:01 UTC, HaudinFlorence commented
The changes for the attributes of Map have been made to fit the default values in LeafletJS. According to this zoom and center have now default values put as None. In the notebook, the user has now to give a value for both for the Map to be properly defined.

2022-04-19 14:49 UTC, martinRenou requested changes

2022-04-19 14:49 UTC, martinRenou commented on docs/source/layers/tile_layer.rst
> +Note that if you want to display a high resolution layer with a quite large zoom, you have to set ``max_zoom`` and ``max_native_zoom`` with equal value.
Maybe we don't need this and rely only on the docstrings?

2022-04-19 14:49 UTC, martinRenou commented on ipyleaflet/leaflet.py
> +        Minimum zoom number the tile source has available. If it is specified, the tiles on all zoom levels lower than minNativeZoom will be loaded from minNativeZoom level and auto-scaled.
```suggestion
        Minimum zoom number the tile source has available. If it is specified, the tiles on all zoom levels lower than min_native_zoom will be loaded from min_native_zoom level and auto-scaled.
```

2022-04-19 14:49 UTC, martinRenou commented on ipyleaflet/leaflet.py
> +        Maximum zoom number the tile source has available. If it is specified, the tiles on all zoom levels higher than maxNativeZoom will be loaded from maxNativeZoom level and auto-scaled.
```suggestion
        Maximum zoom number the tile source has available. If it is specified, the tiles on all zoom levels higher than max_native_zoom will be loaded from max_native_zoom level and auto-scaled.
```

2022-04-19 14:49 UTC, martinRenou commented on ipyleaflet/leaflet.py
>          Maximal zoom value.
```suggestion
        Maximum zoom level of the map. If not specified and at least one GridLayer or TileLayer is in the map, the highest of their max_zoom options will be used instead.
```

2022-04-19 14:49 UTC, martinRenou commented on ipyleaflet/leaflet.py
>          Minimal zoom value.
```suggestion
        Minimum zoom level of the map. If not specified and at least one GridLayer or TileLayer is in the map, the lowest of their min_zoom options will be used instead.
```

2022-04-19 14:49 UTC, martinRenou commented on ipyleaflet/leaflet.py
>          Maximal zoom value.
(taken from the LeafletJS docs)

2022-04-20 09:58 UTC, martinRenou requested changes

2022-04-20 09:58 UTC, martinRenou commented on ipyleaflet/leaflet.py
> +        The maximum zoom level up to which this layer will be displayed (inclusive). Note that if you want to display a high resolution tile layer with a large zoom, you have to set max_zoom and max_
```suggestion
        The maximum zoom level up to which this layer will be displayed (inclusive).
```

The rest of the comment was not technically true. One can set max_zoom and max_native_zoom with different values and still be able to zoom in on a high resolution tile layer.

Also, pointing to external examples may lead to broken links when renaming/moving example notebooks.

2022-04-20 09:58 UTC, martinRenou commented on examples/Max_zoom_tests.ipynb
> +{
Suggestion for the notebook name: `Max_zoom.ipynb`. Also can you clean the cell outputs?

2022-04-21 07:03 UTC, martinRenou requested changes

2022-04-21 07:03 UTC, martinRenou commented on js/src/Map.js
> +import { TileLayer } from 'leaflet';
I suspect this is not needed?

2022-04-22 14:39 UTC, HaudinFlorence commented
Please update galata references. Thanks

2022-04-22 14:49 UTC, martinRenou commented
Triggering CI

2022-04-22 15:13 UTC, merged

2022-04-22 15:13 UTC, martinRenou commented
Thanks!!