Update try it online in the documentation.
jupyter-widgets/ipyleaflet pull request #967
Opened 2022-04-15 18:02 UTC by HaudinFlorence

In the documentation, in index.rst, change the try it online : replace the retrolite directive by 2 links to retro and lab.

2022-04-19 07:22 UTC, martinRenou requested changes

2022-04-19 07:22 UTC, martinRenou commented on docs/source/_contents/ipyleaflet.ipynb
> +{
I guess you did not want to commit this file. We should probably add `docs/source/_contents` to the `.gitignore`

2022-04-19 07:22 UTC, martinRenou commented on docs/source/ipyleaflet.ipynb
> -  },
We probably need to keep this cell around?

2022-04-22 15:30 UTC, martinRenou commented on docs/source/index.rst
> +Directly from this page, you can make a try with ipyleaflet with clicking on `Try it on RetroLab <https://ipyleaflet.readthedocs.io/en/latest/lite/retro>`__ or
```suggestion
You can give ipyleaflet a try in this documentation by clicking on `Try it on RetroLab <https://ipyleaflet.readthedocs.io/en/latest/lite/retro>`__ or
```

2022-04-22 15:40 UTC, merged

2022-05-04 08:25 UTC, jtpio commented
Was the removal motivated by the potentially large initial download of assets?

2022-05-04 08:29 UTC, martinRenou commented
I guess that was the initial motivation yes.

cc. @davidbrochart